/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JComboBox;
import javax.swing.JFrame;

/**
 *
 * @author Anjali
 */
public class SearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchJPanel
     */
    public SearchJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSearchBrand = new javax.swing.JButton();
        btnFindFirsrCar = new javax.swing.JButton();
        btnManufYear = new javax.swing.JButton();
        btnCurrentlyAvai = new javax.swing.JButton();
        btnSeats = new javax.swing.JButton();
        btnUsedByUber = new javax.swing.JButton();
        btnSerialNum = new javax.swing.JButton();
        btnModelNum = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        comBoxCity = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnSearchBrand.setText("Car Brand");

        btnFindFirsrCar.setText("Find The Car");
        btnFindFirsrCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindFirsrCarActionPerformed(evt);
            }
        });

        btnManufYear.setText("Manufacturing Year");

        btnCurrentlyAvai.setText("Available Car");

        btnSeats.setText("Seats");

        btnUsedByUber.setText("Used By Uber");

        btnSerialNum.setText("Serial Number");

        btnModelNum.setText("Model Number");

        jPanel3.setBackground(new java.awt.Color(239, 12, 12));

        comBoxCity.setEditable(true);
        comBoxCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comBoxCityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(458, 458, 458)
                .addComponent(comBoxCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(comBoxCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManufYear)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFindFirsrCar)
                            .addComponent(btnSearchBrand)
                            .addComponent(btnCurrentlyAvai))
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSeats)
                    .addComponent(btnSerialNum)
                    .addComponent(btnUsedByUber)
                    .addComponent(btnModelNum))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCurrentlyAvai, btnFindFirsrCar, btnManufYear, btnModelNum, btnSearchBrand, btnSeats, btnSerialNum, btnUsedByUber});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFindFirsrCar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCurrentlyAvai)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchBrand))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSerialNum)
                        .addGap(18, 18, 18)
                        .addComponent(btnModelNum)
                        .addGap(18, 18, 18)
                        .addComponent(btnUsedByUber))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManufYear)
                    .addComponent(btnSeats))
                .addContainerGap(286, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCurrentlyAvai, btnFindFirsrCar, btnManufYear, btnModelNum, btnSearchBrand, btnSeats, btnSerialNum, btnUsedByUber});

    }// </editor-fold>//GEN-END:initComponents

    private void btnFindFirsrCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindFirsrCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindFirsrCarActionPerformed

    private void comBoxCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comBoxCityActionPerformed
        JComboBox<String> city = new JComboBox<String>();

// add items to the combo box
        city.addItem("Boston");
        city.addItem("New York");
        city.addItem("Miami");

   
        
    }//GEN-LAST:event_comBoxCityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCurrentlyAvai;
    private javax.swing.JButton btnFindFirsrCar;
    private javax.swing.JButton btnManufYear;
    private javax.swing.JButton btnModelNum;
    private javax.swing.JButton btnSearchBrand;
    private javax.swing.JButton btnSeats;
    private javax.swing.JButton btnSerialNum;
    private javax.swing.JButton btnUsedByUber;
    private javax.swing.JComboBox<String> comBoxCity;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
