/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.patient;

import javax.swing.JPanel;
import com.mycompany.healthcaresystem.DataLoader;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Encounter;
import model.HospitalSystem;
import model.Patient;
import model.Person;
import model.VitalSigns;
import ui.LoginPanel;

/**
 *
 * @author Anjali
 */
public class MyHealthPanel extends javax.swing.JPanel {

    /**
     * Creates new form MyHealthPanel
     */
    JPanel containerPanel;
    Patient patient;
    HospitalSystem hospitalSystem;
    public MyHealthPanel(JPanel containerPanel, HospitalSystem system, Patient patient) {
        initComponents();
        this.containerPanel = containerPanel;
        this.hospitalSystem = system;
        this.patient = patient;
        
        populateTable(patient.getEncounterHistory().getEncounters());
        lblName.setText(patient.getfName() + " " + patient.getlName() + ",");
    }
    
    public void populateTable(List<Encounter> encounters){
        DefaultTableModel model = (DefaultTableModel) tblEncounterHistory.getModel();
        model.setRowCount(0);
        
        for(Encounter encounter : encounters ){
            Object[] row = new Object[3];
            row[0] = encounter;
            row[1] = encounter.getVitalSigns();
            row[2] = encounter.getPayment();
            
            model.addRow(row);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPatientName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEncounterHistory = new javax.swing.JTable();
        lblBloodPre = new javax.swing.JLabel();
        lblHeartRate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHeartRate = new javax.swing.JTextField();
        txtBoadyTem = new javax.swing.JTextField();
        txtBloodPre1 = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        lblVitalDetails = new javax.swing.JLabel();
        btnProfile = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPatientName.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        lblPatientName.setForeground(new java.awt.Color(51, 102, 255));
        lblPatientName.setText("Welcome");
        jPanel1.add(lblPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 90, 20));

        tblEncounterHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date", "Vital signs", "Amount paid"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEncounterHistory);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 670, 160));

        lblBloodPre.setText("Blood Pressure:");
        jPanel1.add(lblBloodPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 630, 90, -1));

        lblHeartRate.setText("Heart Rate:");
        jPanel1.add(lblHeartRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 676, -1, 20));

        jLabel4.setText("Body Temperature:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 710, -1, -1));
        jPanel1.add(txtHeartRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 670, 240, 30));
        jPanel1.add(txtBoadyTem, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 710, 240, 30));

        txtBloodPre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodPre1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtBloodPre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 620, 240, 30));

        btnView.setText("View Details");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jPanel1.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 280, 200, 40));

        lblVitalDetails.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblVitalDetails.setForeground(new java.awt.Color(51, 0, 255));
        lblVitalDetails.setText("Encounter Details");
        jPanel1.add(lblVitalDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));

        btnProfile.setText("Update Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });
        jPanel1.add(btnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 200, 40));

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 200, 40));

        jLabel1.setText("Amount paid:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 620, -1, 20));
        jPanel1.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 610, 150, 50));

        lblName.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(51, 102, 255));
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 260, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 438, 1200, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("Summary of visits");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBloodPre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodPre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodPre1ActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblEncounterHistory.getSelectedRow();
     
     if(selectedRowIndex < 0) {
         JOptionPane.showMessageDialog(this, " Please select encounter to view details: ",
                    "FORM ERROR", JOptionPane.ERROR_MESSAGE);
     }     
     else {
        DefaultTableModel model = (DefaultTableModel) tblEncounterHistory.getModel();
        Encounter encounter = (Encounter)tblEncounterHistory.getValueAt(selectedRowIndex, 0);
        VitalSigns vs = encounter.getVitalSigns();
        txtBloodPre1.setText(String.valueOf(vs.getBloodPressure()));
        txtBoadyTem.setText(String.valueOf(vs.getTemperature()));
        txtHeartRate.setText(String.valueOf(vs.getHeartRate()));
        txtAmount.setText(String.valueOf(encounter.getPayment()));
     }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        
        UpdateMyProfile updateProfile = new UpdateMyProfile(containerPanel, this.hospitalSystem, patient);
        containerPanel.add(updateProfile);
        CardLayout cardLayout = (CardLayout)containerPanel.getLayout();
        cardLayout.next(containerPanel);
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:

        containerPanel.removeAll();
        LoginPanel loginPanel = new LoginPanel(containerPanel, hospitalSystem);
        containerPanel.add(loginPanel);
        CardLayout cardLayout = (CardLayout) containerPanel.getLayout();
        cardLayout.next(containerPanel);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblBloodPre;
    private javax.swing.JLabel lblHeartRate;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblVitalDetails;
    private javax.swing.JTable tblEncounterHistory;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtBloodPre1;
    private javax.swing.JTextField txtBoadyTem;
    private javax.swing.JTextField txtHeartRate;
    // End of variables declaration//GEN-END:variables
}
