/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.patient;

import com.mycompany.healthcaresystem.Utils;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.City;
import model.Community;
import model.HospitalSystem;
import model.House;
import model.Patient;
import model.Person;

/**
 *
 * @author Anjali
 */
public class UpdateMyProfile extends javax.swing.JPanel {

    /**
     * Creates new form Update
     */
    JPanel containerPanel;
    HospitalSystem hospitalSystem;
    Patient patient;
    public UpdateMyProfile(JPanel containerPanel, HospitalSystem hospitalSystem, Patient patient) {
        initComponents();
        this.containerPanel = containerPanel;
        this.patient = patient;
        this.hospitalSystem = hospitalSystem;
        
        populateCityComboBox();
        populatePatientDetails();
        
    }
    
    public void populateCityComboBox() {
        for (City city : this.hospitalSystem.getCities()) {
            comboxCity.addItem(city.getName());
            for(Community community : city.getCommunities()) {
                comboxCommunity.addItem(community.getName());
            }
        }
    }
    
    public void populatePatientDetails() {
        txtUsername.setText(patient.getUserName());
        txtPassword.setText(patient.getPassword());
        txtFirst.setText(patient.getfName());
        txtLast.setText(patient.getlName());
        txtDOB.setText(String.valueOf(patient.getAge()));
        txtPhoneNumber.setText(patient.getPhoneNo());
        txtAreaStreetAddress.setText(patient.getHouse().getAddress());
        txtMemberNumber.setText(patient.getMemberId());
        comboxCity.setSelectedItem((String)patient.getHouse().getCommunity().getCity().getName());
        comboxCommunity.setSelectedItem((String)patient.getHouse().getCommunity().getName());
        comboBoxInsuranceGroup.setSelectedItem((String)patient.getInsuranceGroup());
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        comboBoxInsuranceGroup = new javax.swing.JComboBox<>();
        lblLastName = new javax.swing.JLabel();
        txtMemberNumber = new javax.swing.JTextField();
        txtFirst = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtLast = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblPhone = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        lblCommunity = new javax.swing.JLabel();
        comboxCity = new javax.swing.JComboBox<>();
        comboxCommunity = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaStreetAddress = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtZipCode = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Century Schoolbook", 0, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Update Profile");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 840, 40));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 13, 155, 45));

        lblName.setText("First Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        jLabel4.setText("Insurance group:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 588, -1, -1));

        lblDOB.setText("Date of Birth:");
        add(lblDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 306, -1, -1));

        comboBoxInsuranceGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anthem", "Blue Cross Blue Shield", "Cigna", "Harvard Medical School Insurance" }));
        add(comboBoxInsuranceGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, 330, 38));

        lblLastName.setText("Last Name:");
        add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, -1, -1));
        add(txtMemberNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 580, 310, 38));
        add(txtFirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 286, 37));

        jLabel5.setText("Member number:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 596, -1, -1));
        add(txtLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, 293, 37));

        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });
        add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 290, 37));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 655, 230, 47));

        lblPhone.setText("Phone Number:");
        add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 306, -1, -1));

        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });
        add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 296, 293, 37));

        lblCity.setText("City:");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, -1, -1));

        lblCommunity.setText("Community:");
        add(lblCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 396, -1, -1));

        comboxCity.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboxCityItemStateChanged(evt);
            }
        });
        comboxCity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                comboxCityFocusGained(evt);
            }
        });
        comboxCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxCityActionPerformed(evt);
            }
        });
        add(comboxCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 395, 290, 37));

        add(comboxCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 386, 300, 37));

        jLabel1.setText("Street address:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 499, -1, -1));

        txtAreaStreetAddress.setColumns(20);
        txtAreaStreetAddress.setRows(5);
        jScrollPane1.setViewportView(txtAreaStreetAddress);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 481, 333, 45));

        jLabel2.setText("Zip code:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 491, -1, -1));

        txtZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipCodeActionPerformed(evt);
            }
        });
        add(txtZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 481, 97, 37));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 351, 1151, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 533, 1154, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Insurance details");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, -1));

        jLabel6.setText("Password:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 155, -1, -1));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, 286, 33));

        jLabel7.setText("Username:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        txtUsername.setEditable(false);
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 286, 42));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 208, 1210, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Address details");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        containerPanel.remove(this);
        CardLayout cardLayout = (CardLayout)containerPanel.getLayout();
        cardLayout.previous(containerPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        // TODO add your handling code here

        boolean errorFlag = false;
        String errorFields = "Please enter correct values for following fields: \n";
        
        if (!Utils.isValidText(txtFirst.getText())) {
            errorFields += "Invalid First Name\n";
            errorFlag = true;
        }

        if (!Utils.isValidText(txtLast.getText())) {
            errorFields += "Invalid Last Name\n";
            errorFlag = true;
        }

        if (!Utils.isValidText(txtDOB.getText())) {
            errorFields += "Invalid Date of Birth\n";
            errorFlag = true;
        }
        
        if (!Utils.isValidText(txtAreaStreetAddress.getText())) {
            errorFields += "Invalid Street address\n";
            errorFlag = true;
        }

        if(!errorFlag){
            patient.setfName(txtFirst.getText());
            patient.setlName(txtLast.getText());
            patient.setPhoneNo(txtPhoneNumber.getText());

            House house = new House(txtAreaStreetAddress.getText(), patient);
            City city = this.hospitalSystem.getCityByName((String)comboxCity.getSelectedItem());
            Community community = city.getCommunityByName((String)comboxCommunity.getSelectedItem());

            house.setCommunity(community);

            patient.setMemberId(txtMemberNumber.getText());
            patient.setInsuranceGroup((String)comboBoxInsuranceGroup.getSelectedItem());

            JOptionPane.showMessageDialog(this, "Patient profile updated successfully for id : " +patient.getPatienId(),
                "FORM SUCCESS", JOptionPane.INFORMATION_MESSAGE);

        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void comboxCityItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboxCityItemStateChanged
        // TODO add your handling code here:
        City city = this.hospitalSystem.getCityByName((String)comboxCity.getSelectedItem());
        for(Community community : city.getCommunities()) {
            comboxCommunity.addItem(community.getName());
        }

    }//GEN-LAST:event_comboxCityItemStateChanged

    private void comboxCityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboxCityFocusGained
        // TODO add your handling code here:
        City city = this.hospitalSystem.getCityByName((String)comboxCity.getSelectedItem());
        for(Community community : city.getCommunities()) {
            comboxCommunity.addItem(community.getName());
        }
    }//GEN-LAST:event_comboxCityFocusGained

    private void comboxCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxCityActionPerformed

    private void txtZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipCodeActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboBoxInsuranceGroup;
    private javax.swing.JComboBox<String> comboxCity;
    private javax.swing.JComboBox<String> comboxCommunity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtAreaStreetAddress;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtFirst;
    private javax.swing.JTextField txtLast;
    private javax.swing.JTextField txtMemberNumber;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}
