/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.doctor;

import java.awt.CardLayout;
import java.time.LocalDate;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Encounter;
import model.HospitalSystem;
import model.Patient;
import com.mycompany.healthcaresystem.Utils;
import model.VitalSigns;
import ui.LoginPanel;

/**
 *
 * @author Anjali
 */
public class EncounterDetailPanel extends javax.swing.JPanel {

    /**
     * Creates new form EncounterDetailPanel
     */
    HospitalSystem hospitalSystem;
    Patient patient;
    JPanel containerPanel;
    Random random = new Random();
    public EncounterDetailPanel(JPanel containerPanel,Patient patient) {
        initComponents();
        this.patient = patient;
        this.containerPanel = containerPanel;
        populateTable(patient.getEncounterHistory().getEncounters());
        
    }
    
    public void showCarDetails(Encounter encounter) {

    }
    
    public void resetFields() {
        txtBlood.setText("");
        txtHeart.setText("");
        txtTem.setText("");
    }

    
    public void populateTable(List<Encounter> encounters){
        DefaultTableModel model = (DefaultTableModel) tblDisplay.getModel();
        model.setRowCount(0);
        
        for(Encounter encounter : encounters ){
            Object[] row = new Object[3];
            row[0] = encounter;
            row[1] = encounter.getVitalSigns();
            row[2] = encounter.getPayment();
            
            model.addRow(row);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisplay = new javax.swing.JTable();
        lblBlood = new javax.swing.JLabel();
        lblHeart = new javax.swing.JLabel();
        lblTemp = new javax.swing.JLabel();
        txtTem = new javax.swing.JTextField();
        txtBlood = new javax.swing.JTextField();
        txtHeart = new javax.swing.JTextField();
        lblVitDetail = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnAdd1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Encounter Date", "Vital Sign", "Amount Paid"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDisplay);

        lblBlood.setText("Blood Pressure:");

        lblHeart.setText("Heart Rate:");

        lblTemp.setText("Body Tempreature:");

        lblVitDetail.setBackground(new java.awt.Color(51, 51, 255));
        lblVitDetail.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        lblVitDetail.setForeground(new java.awt.Color(51, 0, 255));
        lblVitDetail.setText("Encounter details:");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnView.setText("View Details");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnAdd1.setText("Add new encounter");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1114, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblHeart)
                                    .addComponent(lblBlood)
                                    .addComponent(lblTemp))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBlood)
                                    .addComponent(txtHeart)
                                    .addComponent(txtTem, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblVitDetail))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(398, 398, 398)
                                .addComponent(btnAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblVitDetail)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBlood)
                    .addComponent(txtBlood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeart)
                    .addComponent(txtHeart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemp)
                    .addComponent(txtTem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
        //SplitPane.setRightComponent(loginPanel);
        containerPanel.remove(this);
        CardLayout cardLayout = (CardLayout)containerPanel.getLayout();
        cardLayout.previous(containerPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
     
     int selectedRowIndex = tblDisplay.getSelectedRow();
     
     if(selectedRowIndex < 0) {
         JOptionPane.showMessageDialog(this, " Please select encounter to view details: ",
                    "FORM ERROR", JOptionPane.ERROR_MESSAGE);
     }
     
     else {
        DefaultTableModel model = (DefaultTableModel) tblDisplay.getModel();
        Encounter encounter = (Encounter)tblDisplay.getValueAt(selectedRowIndex, 0);
        VitalSigns vs = encounter.getVitalSigns();
        JOptionPane.showMessageDialog(this, " Vital Sign = Blood Pressure :" + vs.getBloodPressure() + " Heart rate: " + vs.getHeartRate() + " Temperature: " +vs.getTemperature(),
                    "FORM SUCCESS", JOptionPane.INFORMATION_MESSAGE);
     }
     
        
        
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        // TODO add your handling code here:
        boolean errorFlag = false;
        String errorFields = "Please enter correct values for following fields: \n";
        
        if (!Utils.isValidBloodpressure(txtBlood.getText())) {
            errorFields += "Invalid Blood Pressure\n";
            errorFlag = true;
        }

        if (!Utils.isValidHeartRate(txtHeart.getText())) {
            errorFields += "Invalid Heart Rate \n";
            errorFlag = true;
        }

        if (!Utils.isValidTem(txtTem.getText())) {
            errorFields += "Invalid Tempreature \n";
            errorFlag = true;
        }
        
        if(!errorFlag){
            Encounter encounter = this.patient.getEncounterHistory().addNewEncounter(LocalDate.now(), random.nextInt(1000));
            VitalSigns vs = new VitalSigns((Integer.parseInt(txtBlood.getText())), (Integer.parseInt(txtHeart.getText())), 
                    (Integer.parseInt(txtTem.getText())));
            encounter.setVitalSigns(vs);
           
            
            JOptionPane.showMessageDialog(this, "New encounter added successfully for date: " + encounter.getDate().toString(),
                    "FORM SUCCESS", JOptionPane.INFORMATION_MESSAGE);
            resetFields();
            populateTable(this.patient.getEncounterHistory().getEncounters());
        }
        
        else {
            JOptionPane.showMessageDialog(this, "Invalid fields: " + errorFields,
                    "FORM ERROR", JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_btnAdd1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnView;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBlood;
    private javax.swing.JLabel lblHeart;
    private javax.swing.JLabel lblTemp;
    private javax.swing.JLabel lblVitDetail;
    private javax.swing.JTable tblDisplay;
    private javax.swing.JTextField txtBlood;
    private javax.swing.JTextField txtHeart;
    private javax.swing.JTextField txtTem;
    // End of variables declaration//GEN-END:variables
}
