/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JPanel;
import com.mycompany.healthcaresystem.DataLoader;
import com.mycompany.healthcaresystem.Utils;
import javax.swing.JOptionPane;
import model.HospitalSystem;
import model.Patient;
import model.Person;
import ui.doctor.DoctorViewPanel;
import ui.patient.MyHealthPanel;

/**
 *
 * @author Anjali
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    JPanel containerPanel;
    HospitalSystem hospitalSystem;

    public LoginPanel(JPanel containerPanel, HospitalSystem hospitalSystem) {
        initComponents();
        this.containerPanel = containerPanel;
        this.hospitalSystem = hospitalSystem;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUserId = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblRole = new javax.swing.JLabel();
        txtPswd = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        txtUserId.setText("Enter Your UserName");
        txtUserId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserIdFocusGained(evt);
            }
        });
        txtUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIdActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(51, 51, 255));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Log In");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblRole.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        lblRole.setText("Log in to your account");

        txtPswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPswdActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 13)); // NOI18N
        jLabel1.setText("USERNAME:");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 13)); // NOI18N
        jLabel2.setText("PASSWORD:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(421, 421, 421)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPswd, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(534, 534, 534)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(554, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(lblRole)
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPswd, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(60, 60, 60)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(381, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserIdActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        boolean errorFlag = false;
        String errorFields = "";

        if (!Utils.isValidText(txtUserId.getText())) {
            errorFields += "Invalid user name\n";
            errorFlag = true;
        }

        if (!Utils.isValidText(txtPswd.getText())) {
            errorFields += "Invalid password\n";
            errorFlag = true;
        }

        if (errorFlag) {
            JOptionPane.showMessageDialog(this, "Login failed for: " + errorFields,
                    "FORM ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            String userName = txtUserId.getText();
            String password = txtPswd.getText();

            Person person = this.hospitalSystem.getPersonDirectory().authenticateUser(userName, password);
            if(person == null) {
                person = this.hospitalSystem.getPatientDirectory().authenticateUser(userName, password);
            }
            if (person != null) {
                if (person instanceof Patient) {
                    MyHealthPanel patientPanel = new MyHealthPanel(containerPanel, hospitalSystem, (Patient)person);
                    //SplitPane.setRightComponent(patientPanel);
                    containerPanel.add(patientPanel);
                    CardLayout cardLayout = (CardLayout) containerPanel.getLayout();
                    cardLayout.next(containerPanel);
                } else {
                    DoctorViewPanel doctor = new DoctorViewPanel(containerPanel, hospitalSystem, person);
                    //SplitPane.setRightComponent(patientPanel);
                    containerPanel.add(doctor);
                    CardLayout cardLayout = (CardLayout) containerPanel.getLayout();
                    cardLayout.next(containerPanel);
                }

            }
            else {
                JOptionPane.showMessageDialog(this, "No user found with above credentials ",
                    "FORM ERROR", JOptionPane.ERROR_MESSAGE);
            }

        }


    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUserIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserIdFocusGained
        // TODO add your handling code here:

        txtUserId.setText("");

    }//GEN-LAST:event_txtUserIdFocusGained

    private void txtPswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPswdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblRole;
    private javax.swing.JPasswordField txtPswd;
    private javax.swing.JTextField txtUserId;
    // End of variables declaration//GEN-END:variables
}
